### PR TITLE
Retain original order of css rules

### PR DESCRIPTION
**Pull request by sunnavy**
This is mainly to handle parent-children-like css properties like "border" and "border-bottom", in which case the order matters.

Besides it, the other tiny change is to handle "at" rules like "@font-face{...}", where no whitespace occurs between ID and "{".

Thanks!
-sunnavy

### CODE REVIEW

**Comment by cbrandtbuffalo** [comment]
Hi @kamelkev, are you planning on a new CPAN release with these updates?

**Comment by kamelkev** [comment]
Hi Jim,Appreciate the poke.Had gotten distracted, but presuming that the original CPAN interface works the way it used to I should be able to this weekend.Are you leveraging this library as well, or following up for completeness purposes? I am continually amazed that this is used in 2023 :-)On Feb 28, 2023, at 9:19 AM, Jim Brandt ***@***.***> wrote:﻿
Hi @kamelkev, are you planning on a new CPAN release with these updates?

**Comment by kamelkev** [comment]
@sunnavy @cbrandtbuffalo 4018 dropped on CPAN.

**Comment by cbrandtbuffalo** [comment]
> Are you leveraging this library as well, or following up for completeness purposes? I am continually amazed that this is used in 2023 :-)

I work with Sunnavy and we're using it in Request Tracker to help with formatting in some complicated email. It's working well for us. Thanks for pushing the new release!

**Pull request merged**
